services:
  header.factory:
    class: Vainyl\Http\Factory\HeaderFactory
  header.provider.apache:
    class: Vainyl\Http\Provider\ApacheHeaderProvider
    tags:
      - {name: header.provider, priority: 100}
  header.provider.server:
    class: Vainyl\Http\Provider\ServerHeaderProvider
    tags:
      - {name: header.provider, priority: 200}
  header.provider.chain:
    class: Vainyl\Http\Chain\HeaderProviderChain
  header.provider: '@header.provider.chain'
  header.storage:
    shared: false
    class: Vainyl\Http\Storage\HeaderStorage
    arguments: ['@storage.prototype']
  file.storage: '@storage.prototype'
  cookie.storage:
    shared: false
    class: Vainyl\Http\Storage\CookieStorage
    arguments: ['@storage.prototype']
  stream.factory:
    class: Vainyl\Http\Factory\StreamFactory
  file.factory:
    class: Vainyl\Http\Factory\FileFactory
    arguments: ['@stream.factory', '@file.storage']
  cookie.factory:
    class: Vainyl\Http\Factory\CookieFactory
    arguments: ['@storage.prototype']
  stream.factory:
    class: Vainyl\Http\Factory\StreamFactory
  uri.factory:
    class: Vainyl\Http\Factory\UriFactory
  request.stack:
    class: Vainyl\Http\Proxy\RequestStack
  response.stack:
    class: Vainyl\Http\Proxy\ResponseStack
  emitter.factory.sapi:
    class: Vainyl\Http\Factory\EmitterSapiFactory
  emitter.factory.logger:
    decorates: emitter.factory
    class: Vainyl\Http\Decorator\LoggerEmitterFactoryDecorator
    arguments: ['@emitter.factory.logger.inner', '@logger']
  request.factory:
    class: Vainyl\Http\Factory\RequestFactory
    arguments: ['@header.factory', '@cookie.factory', '@stream.factory', '@header.storage', '@cookie.storage', '@file.storage']
  response.factory:
    class: Vainyl\Http\Factory\RequestFactory
    arguments: ['@header.factory', '@stream.factory', '@header.storage']
  http.factory:
    class: Vainyl\Http\Factory\HttpFactory
    arguments: ['@header.provider', '@request.factory', '@response.factory', '@uri.factory', '@header.factory', '@cookie.factory', '@file.factory', '@stream.factory']