services:
  logger.http:
    synthetic: true
    tags:
      - {name: 'logger', channel: 'http'}
  header.factory:
    class: Vainyl\Http\Factory\HeaderFactory
  header.provider.apache:
    class: Vainyl\Http\Provider\ApacheHeaderProvider
    tags:
      - {name: header.provider, priority: 100}
  header.provider.server:
    class: Vainyl\Http\Provider\ServerHeaderProvider
    tags:
      - {name: header.provider, priority: 200}
  header.provider.chain:
    class: Vainyl\Http\Chain\HeaderProviderChain
    arguments: ['@priority.queue.prototype', '@vector.prototype']
  header.provider: '@header.provider.chain'
  header.storage:
    shared: false
    class: Vainyl\Http\Storage\HeaderStorage
    arguments: ['@map.prototype']
  file.storage: '@map.prototype'
  cookie.storage:
    shared: false
    class: Vainyl\Http\Storage\CookieStorage
    arguments: ['@map.prototype']
  stream.factory:
    class: Vainyl\Http\Factory\StreamFactory
  file.factory:
    class: Vainyl\Http\Factory\FileFactory
    arguments: ['@stream.factory', '@file.storage']
  cookie.factory:
    class: Vainyl\Http\Factory\CookieFactory
    arguments: ['@map.prototype']
  uri.factory:
    class: Vainyl\Http\Factory\UriFactory
  request.stack:
    class: Vainyl\Http\Stack\RequestStack
  response.stack:
    class: Vainyl\Http\Stack\ResponseStack
  emitter.factory:
    class: Vainyl\Http\Factory\EmitterSapiFactory
    public: true
  emitter.factory.logger:
    decorates: emitter.factory
    class: Vainyl\Http\Factory\Decorator\LoggerEmitterFactoryDecorator
    arguments: ['@emitter.factory.logger.inner', '@logger.http']
  request.factory:
    class: Vainyl\Http\Factory\RequestFactory
    arguments: ['@header.factory', '@cookie.factory', '@stream.factory', '@header.storage', '@cookie.storage', '@file.storage']
  response.factory:
    class: Vainyl\Http\Factory\ResponseFactory
    arguments: ['@header.factory', '@stream.factory', '@header.storage']
  http.factory:
    class: Vainyl\Http\Factory\HttpFactory
    arguments:
      - '@header.provider'
      - '@request.factory'
      - '@response.factory'
      - '@uri.factory'
      - '@header.factory'
      - '@cookie.factory'
      - '@file.factory'
      - '@stream.factory'
  app.http:
    class: Vainyl\Http\Application\HttpApplication
    arguments: ['@response.factory']
  app.http.exception:
    decorates: app.http
    decoration_priority: 200
    class: Vainyl\Http\Application\Decorator\ExceptionApplicationDecorator
    arguments: ['@app.http.exception.inner', '@encoder.storage', '@response.factory']
  app.http.stack:
    decorates: app.http
    decoration_priority: 300
    class: Vainyl\Http\Application\Decorator\HttpStackApplicationDecorator
    arguments: ['@app.http.stack.inner', '@request.stack', '@response.stack', '@response.factory']
